import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar, Provider, ThemeProvider } from "./components";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* for client Session */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <Navbar />
            <main className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between flex-1">
              {children}
            </main>
            <Footer />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
